import { useEffect, useState } from "react";
import api from "../lib/http";
type Item={CatalogoMatriculaId:number;Descripcion:string;Activo:boolean;RegistrosAsociados:number};
const catalogs=[{tipo:"TIPO_IDENTIFICACION",label:"Tipo de identificación"},{tipo:"NACIONALIDAD",label:"Nacionalidad"},{tipo:"TIPO_ENCARGADO",label:"Tipo de encargado"}];
export default function SuperAdminCatalogosMatriculaPage(){const [tipo,setTipo]=useState(catalogs[0].tipo),[rows,setRows]=useState<Item[]>([]),[text,setText]=useState(""),[edit,setEdit]=useState<Item|null>(null),[error,setError]=useState("");
async function load(){try{const r=await api.get(`/estudiantes/catalogos-matricula/${tipo}`);setRows(r.data?.data||[]);setError("")}catch(e:any){setError(e.response?.data?.message||"No se pudieron cargar opciones. Aplicá primero el script SQL de catálogo.")}}
useEffect(()=>{void load()},[tipo]);
async function save(){try{if(edit)await api.put(`/estudiantes/catalogos-matricula/${tipo}/${edit.CatalogoMatriculaId}`,{descripcion:text,activo:edit.Activo});else await api.post(`/estudiantes/catalogos-matricula/${tipo}`,{descripcion:text});setText("");setEdit(null);await load()}catch(e:any){setError(e.response?.data?.message||"No se pudo guardar")}}
async function remove(row:Item){try{await api.delete(`/estudiantes/catalogos-matricula/${tipo}/${row.CatalogoMatriculaId}`);await load()}catch(e:any){setError(e.response?.data?.message||"No se pudo eliminar")}}
const active=catalogs.find(x=>x.tipo===tipo)?.label;
return <main style={{maxWidth:1000,margin:"24px auto",padding:20}}><h1>Catálogos de matrícula</h1><p>Administrá opciones usadas por Matrícula + estudiante. Las opciones asociadas solo se pueden inactivar.</p><label>Catálogo <select value={tipo} onChange={e=>setTipo(e.target.value)}>{catalogs.map(c=><option key={c.tipo} value={c.tipo}>{c.label}</option>)}</select></label>{error&&<p role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();void save()}}><input required maxLength={120} value={text} placeholder={`Nueva opción: ${active}`} onChange={e=>setText(e.target.value)}/><button>{edit?"Guardar cambios":"Agregar"}</button>{edit&&<button type="button" onClick={()=>{setEdit(null);setText("")}}>Cancelar</button>}</form><table><thead><tr><th>Descripción</th><th>Estado</th><th>Registros asociados</th><th>Acciones</th></tr></thead><tbody>{rows.map(row=><tr key={row.CatalogoMatriculaId}><td>{row.Descripcion}</td><td>{row.Activo?"Activo":"Inactivo"}</td><td>{row.RegistrosAsociados}</td><td><button onClick={()=>{setEdit(row);setText(row.Descripcion)}}>Editar / estado</button>{row.RegistrosAsociados===0&&<button onClick={()=>void remove(row)}>Eliminar</button>}</td></tr>)}</tbody></table></main>}
